//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradeTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GradeTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string str_Add {
            get {
                return ResourceManager.GetString("str_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Assignment.
        /// </summary>
        public static string str_AddAssignment_Header {
            get {
                return ResourceManager.GetString("str_AddAssignment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Course Details page :
        ///1. Select the tab of the type of assignment
        ///2. Click the Add button on the bottom of the page
        ///2. Enter in the name of the assignment and score
        ///3. Click okay.
        /// </summary>
        public static string str_AddAssignment_TB {
            get {
                return ResourceManager.GetString("str_AddAssignment_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string str_AddCategory_Header {
            get {
                return ResourceManager.GetString("str_AddCategory_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Course Details page :
        ///1. Click the + (plus icon) on the right side at the top of the page
        ///2. Enter in the name of the category and weight
        ///3. Click okay.
        /// </summary>
        public static string str_AddCategory_TB {
            get {
                return ResourceManager.GetString("str_AddCategory_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker - Add Category.
        /// </summary>
        public static string str_AddCategoryWinTitle {
            get {
                return ResourceManager.GetString("str_AddCategoryWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Add Course.
        /// </summary>
        public static string str_AddCourse_Header {
            get {
                return ResourceManager.GetString("str_AddCourse_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Course Selection page :
        ///1. Click the Add button at the bottom of the screen
        ///2. Enter in course name and click Okay.
        /// </summary>
        public static string str_AddCourse_TB {
            get {
                return ResourceManager.GetString("str_AddCourse_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker - Add Course.
        /// </summary>
        public static string str_AddCourseWinTitle {
            get {
                return ResourceManager.GetString("str_AddCourseWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakdown by Category:.
        /// </summary>
        public static string str_BreakdownCategory {
            get {
                return ResourceManager.GetString("str_BreakdownCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string str_Cancel {
            get {
                return ResourceManager.GetString("str_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string str_Category {
            get {
                return ResourceManager.GetString("str_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name:.
        /// </summary>
        public static string str_CategoryName {
            get {
                return ResourceManager.GetString("str_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Weight:.
        /// </summary>
        public static string str_CategoryWeight {
            get {
                return ResourceManager.GetString("str_CategoryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Details.
        /// </summary>
        public static string str_CourseDetails {
            get {
                return ResourceManager.GetString("str_CourseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker - Course Details.
        /// </summary>
        public static string str_CourseDetailsWinTitle {
            get {
                return ResourceManager.GetString("str_CourseDetailsWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Selection.
        /// </summary>
        public static string str_CourseSelection {
            get {
                return ResourceManager.GetString("str_CourseSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string str_Edit {
            get {
                return ResourceManager.GetString("str_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker - Edit Category.
        /// </summary>
        public static string str_EditCategoryWinTitle {
            get {
                return ResourceManager.GetString("str_EditCategoryWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Course Score:.
        /// </summary>
        public static string str_FinalCourseScore {
            get {
                return ResourceManager.GetString("str_FinalCourseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker - Grade Overview.
        /// </summary>
        public static string str_GradeOverviewWinTitle {
            get {
                return ResourceManager.GetString("str_GradeOverviewWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker - Help.
        /// </summary>
        public static string str_HelpWinTitle {
            get {
                return ResourceManager.GetString("str_HelpWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Tracker.
        /// </summary>
        public static string str_MainWinTitle {
            get {
                return ResourceManager.GetString("str_MainWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Score.
        /// </summary>
        public static string str_MaxScore {
            get {
                return ResourceManager.GetString("str_MaxScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string str_Next {
            get {
                return ResourceManager.GetString("str_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        public static string str_Okay {
            get {
                return ResourceManager.GetString("str_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string str_Score {
            get {
                return ResourceManager.GetString("str_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Percent.
        /// </summary>
        public static string str_TotalPercent {
            get {
                return ResourceManager.GetString("str_TotalPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Course Details.
        /// </summary>
        public static string str_ViewDetails_Header {
            get {
                return ResourceManager.GetString("str_ViewDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Course Selection page :
        ///1. Select the course in which you want to view the details
        ///2. Click the Next button on the bottom of the page to the right.
        /// </summary>
        public static string str_ViewDetails_TB {
            get {
                return ResourceManager.GetString("str_ViewDetails_TB", resourceCulture);
            }
        }
    }
}
